#!/usr/bin/env sh

DEPLOYMENT_EXAMPLE_ENV_FILE="${DEPLOYMENT_EXAMPLE_ENV_FILE:-docs/deployment/container-example/.env.local}"

if [ -f "$DEPLOYMENT_EXAMPLE_ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  . "$DEPLOYMENT_EXAMPLE_ENV_FILE"
  set +a
fi

DEPLOYMENT_EXAMPLE_COMPOSE_FILE="${DEPLOYMENT_EXAMPLE_COMPOSE_FILE:-compose.deployment-example.yaml}"
DEPLOYMENT_EXAMPLE_COMPOSE_PROJECT="${DEPLOYMENT_EXAMPLE_COMPOSE_PROJECT:-agent-gateway-deployment-example}"
DEPLOYMENT_EXAMPLE_GATEWAY_PORT="${DEPLOYMENT_EXAMPLE_GATEWAY_PORT:-18080}"
DEPLOYMENT_EXAMPLE_GATEWAY_URL="${DEPLOYMENT_EXAMPLE_GATEWAY_URL:-http://localhost:$DEPLOYMENT_EXAMPLE_GATEWAY_PORT}"
DEPLOYMENT_EXAMPLE_GATEWAY_API_KEYS_FILE="${DEPLOYMENT_EXAMPLE_GATEWAY_API_KEYS_FILE:-./docs/deployment/container-example/secrets/gateway-api-keys.example}"
DEPLOYMENT_EXAMPLE_OPENAI_API_KEY_FILE="${DEPLOYMENT_EXAMPLE_OPENAI_API_KEY_FILE:-./docs/deployment/container-example/secrets/openai-api-key.example}"
DEPLOYMENT_EXAMPLE_SECRET_FILES="${DEPLOYMENT_EXAMPLE_SECRET_FILES:-$DEPLOYMENT_EXAMPLE_GATEWAY_API_KEYS_FILE $DEPLOYMENT_EXAMPLE_OPENAI_API_KEY_FILE}"
DEPLOYMENT_EXAMPLE_PORTS="${DEPLOYMENT_EXAMPLE_PORTS:-$DEPLOYMENT_EXAMPLE_GATEWAY_PORT}"
DEPLOYMENT_EXAMPLE_DIAGNOSE_LOG_TAIL="${DEPLOYMENT_EXAMPLE_DIAGNOSE_LOG_TAIL:-120}"
AGENT_GATEWAY_DEPLOYMENT_EXAMPLE_TOKEN="${AGENT_GATEWAY_DEPLOYMENT_EXAMPLE_TOKEN:-deploy-example-token}"

export DEPLOYMENT_EXAMPLE_COMPOSE_FILE
export DEPLOYMENT_EXAMPLE_COMPOSE_PROJECT
export DEPLOYMENT_EXAMPLE_DIAGNOSE_LOG_TAIL
export DEPLOYMENT_EXAMPLE_ENV_FILE
export DEPLOYMENT_EXAMPLE_GATEWAY_API_KEYS_FILE
export DEPLOYMENT_EXAMPLE_GATEWAY_PORT
export DEPLOYMENT_EXAMPLE_GATEWAY_URL
export DEPLOYMENT_EXAMPLE_OPENAI_API_KEY_FILE
export DEPLOYMENT_EXAMPLE_PORTS
export DEPLOYMENT_EXAMPLE_SECRET_FILES
export AGENT_GATEWAY_DEPLOYMENT_EXAMPLE_TOKEN
