#!/usr/bin/env sh
set -eu

. docs/deployment/container-example/env.sh

printf "deployment example command help\n"
printf "\n"
printf "one-command smoke\n"
printf "  make deployment-smoke              build, validate startup failure, run readiness, request, and cleanup\n"
printf "\n"
printf "first-run setup\n"
printf "  make deployment-bootstrap-secrets  create ignored .env.local and *.local secret files\n"
printf "  make deployment-checklist          confirm local files, Docker, Compose, Node.js, and command order\n"
printf "  make deployment-preflight          fail fast on Docker, compose, port, stale container, and secret issues\n"
printf "\n"
printf "manual run\n"
printf "  make deployment-config             print resolved config without secret values\n"
printf "  make deployment-up                 build and start the gateway container\n"
printf "  make deployment-ready              wait for /readyz and Docker healthcheck\n"
printf "  make deployment-request            send one authenticated echo request\n"
printf "\n"
printf "inspection and cleanup\n"
printf "  make deployment-status             print compose state, readiness, and container health\n"
printf "  make deployment-diagnose           print config, compose state, readiness, health, and recent logs\n"
printf "  make deployment-logs               tail gateway logs\n"
printf "  make deployment-down               stop and remove the example stack\n"
printf "  make deployment-reset              remove ignored local deployment files after shutdown\n"
printf "\n"
printf "resolved defaults\n"
printf "  env_file=%s\n" "$DEPLOYMENT_EXAMPLE_ENV_FILE"
printf "  compose_file=%s\n" "$DEPLOYMENT_EXAMPLE_COMPOSE_FILE"
printf "  compose_project=%s\n" "$DEPLOYMENT_EXAMPLE_COMPOSE_PROJECT"
printf "  gateway_url=%s\n" "$DEPLOYMENT_EXAMPLE_GATEWAY_URL"
printf "  ports_checked_by_preflight=%s\n" "$DEPLOYMENT_EXAMPLE_PORTS"
printf "\n"
printf "override knobs\n"
printf "  DEPLOYMENT_EXAMPLE_ENV_FILE\n"
printf "  DEPLOYMENT_EXAMPLE_COMPOSE_PROJECT\n"
printf "  DEPLOYMENT_EXAMPLE_GATEWAY_PORT\n"
printf "  DEPLOYMENT_EXAMPLE_GATEWAY_URL\n"
printf "  DEPLOYMENT_EXAMPLE_GATEWAY_API_KEYS_FILE\n"
printf "  DEPLOYMENT_EXAMPLE_OPENAI_API_KEY_FILE\n"
printf "  DEPLOYMENT_EXAMPLE_PORTS\n"
printf "  DEPLOYMENT_EXAMPLE_DIAGNOSE_LOG_TAIL\n"
printf "  DEPLOYMENT_EXAMPLE_LOG_TAIL\n"
printf "  DEPLOYMENT_EXAMPLE_WAIT_ATTEMPTS\n"
printf "  DEPLOYMENT_EXAMPLE_WAIT_SECONDS\n"
printf "  AGENT_GATEWAY_DEPLOYMENT_EXAMPLE_TOKEN\n"
