#!/usr/bin/env sh
set -eu

COMPOSE_FILE="${OBSERVABILITY_COMPOSE_FILE:-compose.observability.yaml}"
COMPOSE_PROJECT_NAME="${OBSERVABILITY_COMPOSE_PROJECT:-agent-gateway-observability-demo}"
GATEWAY_URL="${GATEWAY_URL:-http://localhost:8080}"
COLLECTOR_METRICS_URL="${COLLECTOR_METRICS_URL:-http://localhost:9464/metrics}"
PROMETHEUS_URL="${PROMETHEUS_URL:-http://localhost:9090}"
GRAFANA_URL="${GRAFANA_URL:-http://localhost:3000}"
DEMO_PORTS="${OBSERVABILITY_DEMO_PORTS:-3000 4317 4318 8080 9090 9464}"

printf "local observability demo command help\n"
printf "\n"
printf "one-command smoke\n"
printf "  make observability-smoke            preflight, start, wait, generate traffic, inspect, and cleanup\n"
printf "\n"
printf "manual run\n"
printf "  make observability-preflight        fail fast on Docker, Compose, port, and stale-container issues\n"
printf "  make observability-up               build and start gateway, collector, Prometheus, and Grafana\n"
printf "  make observability-ready            wait for gateway and Prometheus readiness\n"
printf "  make observability-traffic          send representative success and rejection requests\n"
printf "\n"
printf "inspection and cleanup\n"
printf "  make observability-status           print compact compose and endpoint state without log output\n"
printf "  make observability-inspect          run gateway, collector, Prometheus, and Grafana checks\n"
printf "  make observability-logs             tail gateway, collector, Prometheus, and Grafana logs\n"
printf "  make observability-down             stop and remove the demo stack\n"
printf "\n"
printf "local endpoints\n"
printf "  gateway_readyz=%s/readyz\n" "$GATEWAY_URL"
printf "  collector_metrics=%s\n" "$COLLECTOR_METRICS_URL"
printf "  prometheus=%s\n" "$PROMETHEUS_URL"
printf "  grafana_dashboard=%s/d/agent-gateway-ops/agent-gateway\n" "$GRAFANA_URL"
printf "\n"
printf "resolved defaults\n"
printf "  compose_file=%s\n" "$COMPOSE_FILE"
printf "  compose_project=%s\n" "$COMPOSE_PROJECT_NAME"
printf "  ports_checked_by_preflight=%s\n" "$DEMO_PORTS"
printf "\n"
printf "override knobs\n"
printf "  OBSERVABILITY_COMPOSE_FILE\n"
printf "  OBSERVABILITY_COMPOSE_PROJECT\n"
printf "  OBSERVABILITY_DEMO_PORTS\n"
printf "  GATEWAY_URL\n"
printf "  COLLECTOR_METRICS_URL\n"
printf "  PROMETHEUS_URL\n"
printf "  GRAFANA_URL\n"
printf "  OBSERVABILITY_READY_WAIT_ATTEMPTS\n"
printf "  OBSERVABILITY_READY_WAIT_SLEEP_SECONDS\n"
printf "  OBSERVABILITY_LOG_TAIL\n"
printf "  OBSERVABILITY_SMOKE_LOG_TAIL\n"
printf "  OBSERVABILITY_SMOKE_WAIT_ATTEMPTS\n"
printf "  OBSERVABILITY_SMOKE_WAIT_SLEEP_SECONDS\n"
printf "  AGENT_GATEWAY_DEMO_TOKEN\n"
